name: dart_utils
description: Some common definitions useful for generic Dart code.
version: 2.0.0
# homepage: https://www.example.com
author: Wilson, Marvin (jw9615) <jw9615@att.com>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  quiver: ^2.1.2+1
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.9.4
  test_coverage: ^0.4.0
