name: dart_utils
description: Some common definitions useful for generic Dart code.
version: 2.0.1
# homepage: https://www.example.com
author: Wilson, Marvin (jw9615) <jw9615@att.com>

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  quiver: ^2.1.5

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.7
  test_coverage: ^0.5.0
